### ISSUE TITLE
关于文档若干改进

### ISSUE THREAD

**Issue by fduxiao** [Tencent/TSW#112]
1. [Quick start](https://tswjs.org/guide/introduce/quickstart)里面不要加入`高手可以跳过`之类字眼，技术文档应该严肃。
2. 公开文档的源代码（这样遇到以上问题可以直接交PR）

**Comment by huangyoukun** [comment]
1.文档已更新~
2.考虑过文档也放在github上来，但目前文档是动态生成的（左目录+上导航），并不是静态文件，放上来阅读性会比较差，请理解。文档有问题可以直接提交issue给我们，第一时间更新。

**Comment by mapleeit** [comment]
感觉可以把[教程](https://tswjs.org/guide/index)和[手册](https://tswjs.org/doc/api/index)开源出来给大家更改 @huangyoukun ，主页可能有开放平台的原因不好开源，但是这两个文档页应该是可以的。如果ok的话，我可以来搞一下

**Comment by huangyoukun** [comment]
@mapleeit 可以啊，开吧
