### ISSUE TITLE
官网cover引用这张图开车是不是有点不合时宜？？？

### ISSUE THREAD

**Issue by icepoint0** [Tencent/TSW#12]
![image](https://user-images.githubusercontent.com/12691638/40296401-0b4a36f0-5d0f-11e8-84d0-76c7fd89ab0e.png)

机场五块 走不

**Comment by zhuweiyou** [comment]
开车别太快，营养跟不上

**Comment by icepoint0** [comment]
![image](https://user-images.githubusercontent.com/12691638/40296692-ecc658de-5d0f-11e8-90cf-5fce0072c7c7.png)

**Comment by icepoint0** [comment]
为什么老要我去机场。。

**Comment by dariondiao** [comment]
为防止大家营养跟不上，还是不开车了

**Comment by RobinzZH** [comment]
@Jer-X JQ换了个域名，再试试？

**Comment by huangyoukun** [comment]
已删除这个封面~

**Comment by susanforme** [comment]
不合时宜
