### ISSUE TITLE
关于node_modules目录的建议

### ISSUE THREAD

**Issue by liweinan0423** [Tencent/TSW#15]
我是在知乎上看到然后过来的。如果这个项目的node_modules目录中包含有修改过的第三方库，我建议可以创建一个vendor目录，然后把修改过的代码挪过去，这样更符合业界的标准做法。

而对于鹅厂内部的库，如果不想push到npm，简单的做法是可以放在顶层的lib目录，更高级一点的做法是可以使用lerna来管理。

**Comment by huangyoukun** [comment]
收到，等 @RobinzZH 来调整目录版本push上来就close~

**Comment by RobinzZH** [comment]
已经调整了版本，调整后按npm管理部分依赖，其他放在lib等目录当中
