### ISSUE TITLE
关于项目的部分小建议

### ISSUE THREAD

**Issue by wupengFEX** [Tencent/TSW#16]
粗略看了下，说几点优化建议（只是个人建议，有更好的方式最好）：
1. 单元测试
    - 尽快完善测试用例吧...
    - 有可能的话加上 `mocha+karma+travis+coveralls` 类似的一些平台进行集成测试（当然不一定是前面说的几个，可以根据自己的需求来选择），并附加 badge，这样开发者也能知道项目概况；
    - `npm script` 里面没必要调用 `node_modules` 路径，`install` 后直接可以用命令来调用；
2. 项目结构
    - 项目中文件没有区分度，很多都堆积在 bin 目录下（可能是历史原因，但开源毕竟开源，很多人在看），希望可以从整体架构层面优化一些（不带历史包袱最好，虽然看样子不可能）；
    - readme 里面的图片直接仍在最上层文件夹，这让人就受不了了，如果后续里面有很多图那是不是得全放在下面？所以建议有个 `static/resource` 的概念，统一管理资源类；
3. changelog
    - 开源按照开源的套路走，用 GitHub release note 不是更专业点么？
4. 版本概念
    - 现在我看还没有版本的概念（tags 管理），加上对以后维护也有一定好处。
4. 依赖 && 配置
    - `/test`, `/bin` 下面都有 `node_module`，不知道为什么要这么做？如果是需要改动源码来满足需求的话，建议还是自己开发吧...如果实在开发不了，我看里面部分 module 是 MIT 的，改动下自己发个 npm 包也能解决这个问题；
    - 加入 `.gitignore` 和 `.editorconfig` 之类的配置文件统一规范整个项目吧。

其他一些点就不说了，很多人在知乎上都提过，开源是一件非常棒的事，也非常期望能够做好。

**Comment by RobinzZH** [comment]
1. 单元测试方面： 用例正在安排补充，已接入mocha+travis ，ESLint也在接，会按需增加相关测试框架
2. 目录结构正在更改优化中，后续再考虑整体架构层面的优化调整。
3. 这周处理下，之后会按照开源套路
4. 刚开源，变动比较大，下周整理后，按版本走，Tags管理搞起
5. 这个今天更改了一个版本，优化了下配置和node_module问题，改成npm管理依赖

正在学习开源流程与优化，希望大家一起加入进来，让TSW能变得更好。
