### ISSUE TITLE
这句话是要表达什么？

### ISSUE THREAD

**Issue by AnonymousBoy1** [Tencent/TSW#17]
这句话是句话吗？用机器翻译过来的？
[https://github.com/Tencent/TSW](https://github.com/Tencent/TSW)中文介绍的第一大项
“TSW 支持用户纬度的抓包”中第一小项

“对于染色的用户”，这是什么？

**Comment by Lizhooh** [comment]
我也觉得奇怪，“染色”是啥意思。

**Comment by alsotang** [comment]
@mapleeit 这个地方是维度还是纬度？

**Comment by mapleeit** [comment]
@alsotang 是“维度”
