### ISSUE TITLE
现有的TSW源码与业务代码整合问题？

### ISSUE THREAD

**Issue by liyanlong** [Tencent/TSW#170]
如果我有多个koa的应用项目，彼此没有任何联系。

那么是 一个tsw + 一个koa项目整合在一起，还是一个全局的tsw，通过配置挂载多个koa项目。哪种方式会更好？

**Comment by huangyoukun** [comment]
@liyanlong 后者比较好，1+N挂载。

前者要求： 从开发-测试-生产    流程上都是完全不相关，即独立部署的
后者只需 ：这个可以在开发、测试、生产环境上保持相同实例，代码是全同。生产环境独立部署的要求，只需要从流量上流增加控制点，导入不同的分组即可。

**Comment by liyanlong** [comment]
@huangyoukun 如果以后 tsw整合成了一个npm仓库包，然后引入后对外暴露一些配置或者api的话。是不是对项目整合更加友好。

**Comment by sunYanxl** [comment]
@liyanlong 现在可以通过npm install @tswjs/tswjs 来安装包啦 :laughing:

**Comment by sunYanxl** [comment]
https://www.npmjs.com/package/@tswjs/tswjs

**Comment by meteorlxy** [comment]
@sunYanxl 现在cli不支持`--config`传入配置文件了吗？

**Comment by huangyoukun** [comment]
npm已经支持，close~
