### ISSUE TITLE
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT HON env variable.

### ISSUE THREAD

**Issue by fairyly** [Tencent/TSW#18]
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT HON env variable.

这个还依赖 Python呢

**Comment by huangyoukun** [comment]
应该是调用了npm install导致的，晚点push个版本上来验证下，如果不能恢复正常，加QQ 345680969定位下原因

**Comment by BlackHole1** [comment]
@fairyly  因为你安装的时候安装了gyp这个package,而这个package在win下是有问题的.因为需要实时编译,而nodejs没有编译的功能,所以需要python来帮助编译才可以,而python也是借助了vs2008以上的编译器才能编译好,所以你如果在win下安装,需要安装`python2.7.*`和`vs2015`才有可能安装成功,推荐还是在linux上执行安装把

**Comment by BlackHole1** [comment]
顺带说一下,这是一个没有正面解答的`issues`, 在没有完成解答前,不推荐直接关闭这个`issues`. @huangyoukun
