### ISSUE TITLE
可以对接eggjs么

### ISSUE THREAD

**Issue by carmanchang** [Tencent/TSW#27]
你好，最近在使用eggjs进行开发，想要接入tsw，要怎么接入呢，看官方没有相应例子，能不能提供下现在常用一些框架的接入demo

**Comment by huangyoukun** [comment]
eggjs不在可集成框架列表内
目前已知的可集成框架：koa|express|hapi [文档地址](https://tswjs.org/doc/api/framework)

**Comment by huangyoukun** [comment]
已支持 https://github.com/Tencent/TSW/pull/141
