### ISSUE TITLE
TSW 可以支持POST请求转发到测试环境吗？

### ISSUE THREAD

**Issue by alamozhou** [Tencent/TSW#273]
需求背景：有些接口要开放给第三方平台调用，并且处于安全考虑只能用post请求。当接口相关的逻辑变更时，让调用方更改难度太大，又无法转发到测试环境验证，只能外网验证。

希望TSW支持POST请求转发到测试环境

**Comment by RobinzZH** [comment]
目前测速环境转发是在请求body解析之前获取用户身份标志信息的
参考：[/bin/proxy/http.route.js#L507](https://github.com/Tencent/TSW/blob/66a5f0d034ac25996bd7090a7bc92833486f0a48/bin/proxy/http.route.js#L507)

对特定转发请求，线上服务无需进行body解析等额外检查
在parsebody后再做一次检查应该可以解决这个问题

**Comment by RobinzZH** [comment]
2.0 已经不区分 method进行测试环境转发了，可以自行根据req定义染色规则
