### ISSUE TITLE
请问一下项目里面的plug是什么作用

### ISSUE THREAD

**Issue by shenzekun** [Tencent/TSW#303]
![image](https://user-images.githubusercontent.com/21151080/53097378-49a00d00-355c-11e9-987e-1f2cef52a14a.png)

源码
![image](https://user-images.githubusercontent.com/21151080/53097220-e6ae7600-355b-11e9-8fdd-4ff7cc87712b.png)
如题目前看了源码是返回了 require，里面使用 global.plug，重新写了一些逻辑，但是具体的作用是什么，为什么不直接用 require 呢

**Comment by huangyoukun** [comment]
plug可以加载内置模块，主要修改点是增加了require的内部寻址目录。require无法加载TSW内置的模块

**Comment by shenzekun** [comment]
@huangyoukun 好的，感谢
