### ISSUE TITLE
What's the meaning of the `isWindows`

### ISSUE THREAD

**Issue by jdz321** [Tencent/TSW#315]
https://github.com/Tencent/TSW/blob/master/bin/tsw/util/isWindows.js#L12

both macOS and Windows return `true`

**Comment by RobinzZH** [comment]
In a certain period of time, it(`isWindows`) was used for env judgment (dev or prod, most developers use Windows), however later developers in the Mac modified it directly.
we have used new object(`isWin32Like`) instead, and `isWindows` need to be correct.

**Comment by jdz321** [comment]
Will it be more appropriate to use exact flags, such as environment variables, startup arguments
or configuration items.

**Comment by mapleeit** [comment]
2.0 already removed this method.
