### ISSUE TITLE
tsw+webpack dev middle做本地开发，热更新很慢，希望支持配置解决，谢谢

### ISSUE THREAD

**Issue by Dengxianyu** [Tencent/TSW#334]
参考KM文章中：http://km.oa.com/articles/show/358254?kmref=search&from_page=1&no=4
里面也写到“我们node服务用的是tsw作为接入层，由于tsw设置了默认超时。当长时间保持http链接时，会被tsw认为是超时链接，被默认关闭。解决办法也很简单，对于content-type为event-stream不做超时处理”
咨询过作者，是改动了tsw源码去实现的。可否不改动tsw实现呢，希望指点

**Comment by zkd8907** [comment]
把[config](https://github.com/Tencent/TSW/blob/master/bin/tsw/default/config.default.js)文件里的timeout设置长一些是否可以解决你的问题？

**Comment by Zack921** [comment]
tsw1.0遗留issue，先关了～
