### ISSUE TITLE
文档与代码是否没同步？

### ISSUE THREAD

**Issue by SzHeJason** [Tencent/TSW#403]
## 描述
最近业务想使用新版的 TSW，上来根据 README.md 运行后，看了下官方文档，发现官方文档的很多内容都被移除了吧？像 plug 这种引入都会报错
控制台也不能打印出任何消息，有点蒙蔽

## 环境
Branch: Master
Commit: c34c625146fca4f36078b7e60a1288403dc4eea7
System: MacOS
NodeJS: 12.6.2

**Comment by mapleeit** [comment]
是的，tswjs.org 这里的文档是 1.0 的，对于 2.0 来说没有那么多接口。一切内容以 README 为主

**Comment by mc-zone** [comment]
README对于 config 好像也只有关于插件和 winston 的讲解，没有列出其他的配置项。比如新版本怎么调整 loglevel 呢，源码有 `setLogLevel` 这个要自己写插件来设置？

**Comment by Zack921** [comment]
我提个issue，在官网里新增2.0文档

**Comment by Zack921** [comment]
官方文档已更新
