### ISSUE TITLE
关掉一些log的默认打印

### ISSUE THREAD

**Issue by 416377966** [Tencent/TSW#413]
默认打印的日志太多了，配置去掉一些

**Comment by Zack921** [comment]
晚点我想想怎么优化～

**Comment by Zack921** [comment]
目前看下来，是开放平台插件默认打印的日志太频繁了，暂定给它新加个配置项，配置后去掉默认打印
![image](https://user-images.githubusercontent.com/32858043/120290497-f7322700-c2f4-11eb-930d-bdce79e42734.png)

**Comment by Zack921** [comment]
看了一下 日志虽然是有开放平台插件触发的，但是是因为tsw hack了请求才打印了，如果贸然关掉，可能不方便业务方排除错误。

**Comment by Zack921** [comment]
经讨论，提供个配置项，配置后正常情况下不打印log，异常情况下打印出报错的上下文

**Comment by Zack921** [comment]
> 默认打印的日志太多了，配置去掉一些

已发布，将tsw版本升级到**2.4.0**以上，同时在`tswconfig.js`上加上一个 `cleanLog:true` 的配置就可以关掉默认打印
![image](https://user-images.githubusercontent.com/32858043/120416522-e1be0b00-c38f-11eb-8491-b9e524ac2bd3.png)
