### ISSUE TITLE
这个和腾讯微服务观测平台TSW 有什么关系吗？

### ISSUE THREAD

**Issue by Midqiu** [Tencent/TSW#434]
能用这个客户端连接 腾讯微服务观测平台TSW 投递日志吗？

**Comment by Zack921** [comment]
腾讯微服务观测平台是指？
现在TSW 官方提供的公共服务平台是这个：https://tswjs.org
上报教程：
https://github.com/Tencent/TSW/blob/master/docs/use-open-platform.md

**Comment by Midqiu** [comment]
这个是腾讯云的腾讯微服务观测平台 TSW       https://cloud.tencent.com/document/product/1311/50754

**Comment by Zack921** [comment]
这个感觉像是tsw1.0的用法，目测部署了tsw1.0的runtime在腾讯云吧
现在tsw2.0就是个npm包～
