### ISSUE TITLE
数据收集符合GDPR吗？

### ISSUE THREAD

**Issue by oscarhong** [Tencent/TSW#48]
GDPR今天开始实施了。业务需求要符合GDPR。请问这个服务器符合相关要求吗？

**Comment by huangyoukun** [comment]
## 安全和隐私

1. 开放平台服务方已采取的措施
    1. 项目信息是完全私密的，采用`appid`隔离，非项目成员无权访问
    1. 抓包、日志敏感数据，`存储/缓存`使用`appid+appkey`加盐加密，规避非授权访问
    1. `appkey`落地`存储/缓存`前，进行了加盐加密，规避脱库
1. 开放平台使用方应该遵循的原则
    1. 保持`appkey`私密，因用于存储加密，不提供修改能力
    1. 如果`appkey`意外泄漏，请更换`appid`和`appkey`
    1. 项目成员合理授权，定期清理成员名单
1. 更高的安全和隐私需求，推荐使用私有化部署。[了解一下？](https://tswjs.org/guide/advance/private)
