### ISSUE TITLE
全息日志未展开时无法看到请求路径

### ISSUE THREAD

**Issue by 7Finn** [Tencent/TSW#544]
如图：
![image](https://user-images.githubusercontent.com/14886503/227164211-a62f37f1-34ff-49f5-96d0-607dc9236128.png)
![image](https://user-images.githubusercontent.com/14886503/227182928-5127ea8b-2d99-4178-af7b-83a79b72de03.png)

在未展开时只有 /，但展开后是能看到详细路径的。
静态数据可以，但POST请求不行
![image](https://user-images.githubusercontent.com/14886503/227164519-c3de766c-147a-4ea7-9a08-231df830cc04.png)

tswconfig.js
```
const OpenPlatformPlugin = require('@tswjs/open-platform-plugin');
const uinRegEx = /.../;

module.exports = {
  plugins: [
    new OpenPlatformPlugin({
      reportStrategy: 'proxied',
      getUid: (req) => {
        const { cookie } = req.headers;
        if (!cookie) return;
        return (cookie.match(uinRegEx) || [])[1] || '';
      },
      getProxyInfo: () => ({
        port: 80,
        name: '..',
        group: '..',
        groupName: '...',
        desc: '..',
        order: 30,
        alphaOnly: process.env.NODE_ENV !== 'test',
        alphaList: [
        ],
      }),
    }),
  ],
};

```

APP_ID: tsw2104
用户Uid: 879788904
时间：2023-03-23 17:30~17:50
nodejs: 14.15.0
node框架: express@4.17.1
@tswjs/tsw: 2.6.4

**Comment by RobinzZH** [comment]
已沟通确认，这是express修改了req.url导致的，业务可自行兼容
