### ISSUE TITLE
用法含义错误

### ISSUE THREAD

**Issue by zhuangzhuang** [Tencent/TSW#76]
![6](https://user-images.githubusercontent.com/521058/40636595-49a04d6c-6332-11e8-9ce8-3f6318b655a2.png)

String.replace本意用来替换的，而且也里面函数也没返回值
如果只是用来提取数据应该用更明确的方法

**Comment by huangyoukun** [comment]
多值的时候，楼主提供的方法是有bug的，只会执行一次，replace就没这个问题~
原写法用reaplce没有问题

**Comment by huangyoukun** [comment]
好像这里不需要考虑多值，用楼主说的~

**Comment by zhuangzhuang** [comment]
@huangyoukun 主要不是多值的而是函数的语义, 就和 `_.forEach` vs `_.map`, ` _.map`也确实可以代替`_.forEach`，但是语义明显不一样
